x-airflow-common: &airflow-common
  build: .
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    PYTHONPATH: /opt/airflow
  volumes:
    - ./dags:/opt/airflow/dags
    - ./pipeline:/opt/airflow/pipeline
    - ./scripts:/opt/airflow/scripts
    - ./data:/opt/airflow/data
    - ./logs:/opt/airflow/logs

services:

  postgres:
    image: postgres:13
    restart: always  
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ================= INIT (SOLO PRIMERA VEZ) =================
  airflow-init:
    <<: *airflow-common
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: /bin/bash
    command: >
      -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --firstname Gian
      --lastname User
      --role Admin
      --email admin@email.com
      --password admin
      "

  # ================= WEBSERVER =================
  airflow-webserver:
    <<: *airflow-common
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    command: webserver
    restart: always

  # ================= SCHEDULER =================
  airflow-scheduler:
    <<: *airflow-common
    depends_on:
      postgres:
        condition: service_healthy
    command: scheduler
    restart: always

  # ================= TRIGGERER =================
  airflow-triggerer:
    <<: *airflow-common
    depends_on:
      postgres:
        condition: service_healthy
    command: triggerer
    restart: always

volumes:
  postgres-db-volume: